name = "sui-events-sync"
main = "workers/src/index.ts"
compatibility_date = "2024-01-01"

# Durable Objects 配置
[[durable_objects.bindings]]
name = "SYNC_STATE"
class_name = "SyncState"

# 迁移配置
[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncState"]

# 环境变量
[vars]
LUMA_API_KEY = "your-luma-api-key"
GOOGLE_SHEET_ID = "your-google-sheet-id"
GOOGLE_CLIENT_EMAIL = "your-service-account-email"
GOOGLE_PRIVATE_KEY = "your-private-key" 